services:
  backend:
    image: ${IMAGE_REPOSITORY}/backend:${IMAGE_TAG}
  worker:
    image: ${IMAGE_REPOSITORY}/backend:${IMAGE_TAG}
  frontend:
    image: ${IMAGE_REPOSITORY}/frontend:${IMAGE_TAG}
